name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:stable
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          yes | buildozer android debug || true
          ls -la bin/ || true
          if [ ! -f bin/*.apk ]; then
            echo "APK не создан"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: warfacts-apk
          path: bin/*.apk
